site_name: PyStringToolkit
site_description: Handy string utilities for Python
repo_url: https://github.com/RaeesFatima/pystringtoolkit-documentation
theme:
  name: material
  logo: assets/PST.png
  favicon: assets/logo.png
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_toc_entry: false
            members: true
            inherited_members: true
            docstring_style: google